title: jsideas
description: > # this means to ignore newlines until "baseurl:"
  a novice's journey into data science
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "http://jsideas.net" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: https://twitter.com/junsik_whang

# Author Settings
author: Junsik Hwang # add your name
author-img: author.jpg # add your photo
about-author: I do data analytics and modelling for a living and for fun # add description
social-twitter: junsik_whang
social-github: junkwhinger # add your Github handle
social-linkedin: jswhang # add your Linkedin handle
social-email: junsik.whang@gmail.com # add your Email address

# Disqus
discus-identifier: jsideas # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-youtube

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
