# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: pygments
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-giphy
  - kramdown

# Site settings
title: "jsideas"
description: > # this means to ignore newlines until "email:"
   a novice's journey into data science

email: junsik.whang@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Junsik Whang'
author: 'Junsik Whang'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://jsideas.net" # the base hostname & protocol for your site
baseurl: 

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/junsik_whang
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/junkwhinger
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
